name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 (GitHub-certified)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Build with Gradle Wrapper
      - name: Build with Gradle
        run: ./gradlew build

  # Dependency Submission Job
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 (GitHub-certified)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Submit Dependency Graph (alternative or script if required)
      - name: Submit Dependency Graph
        run: |
          echo "Submitting dependency graph (script this step if necessary)"